# Generated by Django 2.0.4 on 2018-05-09 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainteam',
            fields=[
                ('teamid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=600)),
            ],
            options={
                'db_table': 'mainteam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'membership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teammember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('age', models.IntegerField(null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teammember',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Teammember'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Mainteam'),
        ),
        migrations.AddField(
            model_name='mainteam',
            name='members',
            field=models.ManyToManyField(through='djangoapp.Membership', to='djangoapp.Teammember'),
        ),
    ]
