# Generated by Django 2.0.4 on 2018-05-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_auto_20180521_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
